apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: recreate-ns
  labels:
    app: online-shop
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - image: amitabhdevops/online_shop
        name: online-shop
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
